//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anno
    {
        public Anno()
        {
            this.TarifaCarro = new HashSet<TarifaCarro>();
            this.TemporadaAvion = new HashSet<TemporadaAvion>();
            this.TemporadaExcursion = new HashSet<TemporadaExcursion>();
            this.Temporada_Hotel = new HashSet<Temporada_Hotel>();
            this.TemporadaPaquete = new HashSet<TemporadaPaquete>();
            this.Temporada_Reduccion = new HashSet<Temporada_Reduccion>();
            this.Temporada_Suplemento = new HashSet<Temporada_Suplemento>();
            this.TemporadaEmpresa = new HashSet<TemporadaEmpresa>();
            this.TemporadaRental = new HashSet<TemporadaRental>();
        }
    
        public int IdAnno { get; set; }
        public string anno1 { get; set; }
    
        public virtual ICollection<TarifaCarro> TarifaCarro { get; set; }
        public virtual ICollection<TemporadaAvion> TemporadaAvion { get; set; }
        public virtual ICollection<TemporadaExcursion> TemporadaExcursion { get; set; }
        public virtual ICollection<Temporada_Hotel> Temporada_Hotel { get; set; }
        public virtual ICollection<TemporadaPaquete> TemporadaPaquete { get; set; }
        public virtual ICollection<Temporada_Reduccion> Temporada_Reduccion { get; set; }
        public virtual ICollection<Temporada_Suplemento> Temporada_Suplemento { get; set; }
        public virtual ICollection<TemporadaEmpresa> TemporadaEmpresa { get; set; }
        public virtual ICollection<TemporadaRental> TemporadaRental { get; set; }
    }
}
