//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        public Avion()
        {
            this.NomAvionClase = new HashSet<NomAvionClase>();
            this.NomTempAvionClase = new HashSet<NomTempAvionClase>();
        }
    
        public int idVuelo { get; set; }
        public string numVuelo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int idEmpresa { get; set; }
        public System.DateTime tsalida { get; set; }
        public System.DateTime tllegada { get; set; }
        public string horallegada { get; set; }
        public string horasalida { get; set; }
        public Nullable<int> idTipoAvion { get; set; }
        public Nullable<int> idOrigenVuelo { get; set; }
        public Nullable<int> idDestinoVuelo { get; set; }
        public Nullable<int> pasajeros { get; set; }
    
        public virtual OrigenVuelo OrigenVuelo { get; set; }
        public virtual DestinoVuelo DestinoVuelo { get; set; }
        public virtual ICollection<NomAvionClase> NomAvionClase { get; set; }
        public virtual ICollection<NomTempAvionClase> NomTempAvionClase { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual TipoAvion TipoAvion { get; set; }
    }
}
