//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadena
    {
        public Cadena()
        {
            this.Hotel = new HashSet<Hotel>();
        }
    
        public int idCadena { get; set; }
        public string cadena_ { get; set; }
        public string logo_cadena { get; set; }
        public string descrpcion_cadena { get; set; }
    
        public virtual ICollection<Hotel> Hotel { get; set; }
    }
}
