//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        public Carro()
        {
            this.OficPerCar = new HashSet<OficPerCar>();
        }
    
        public int idCarro { get; set; }
        public string foto_carro1 { get; set; }
        public string foto_carro2 { get; set; }
        public string foto_carro3 { get; set; }
        public int idtipologia_carro { get; set; }
        public string descripcion_carro { get; set; }
        public int idempresa { get; set; }
        public string name { get; set; }
        public string transmision { get; set; }
        public Nullable<int> pasajeros { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Tipologia_Carro Tipologia_Carro { get; set; }
        public virtual ICollection<OficPerCar> OficPerCar { get; set; }
    }
}
