//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clase
    {
        public Clase()
        {
            this.NomClaseCatTarAvi = new HashSet<NomClaseCatTarAvi>();
            this.NomAvionClase = new HashSet<NomAvionClase>();
            this.NomTempAvionClase = new HashSet<NomTempAvionClase>();
        }
    
        public int idClase { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<NomClaseCatTarAvi> NomClaseCatTarAvi { get; set; }
        public virtual ICollection<NomAvionClase> NomAvionClase { get; set; }
        public virtual ICollection<NomTempAvionClase> NomTempAvionClase { get; set; }
    }
}
