//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Avion = new HashSet<Avion>();
            this.Carro = new HashSet<Carro>();
            this.Excursion = new HashSet<Excursion>();
            this.OficinaRenta = new HashSet<OficinaRenta>();
            this.Paquete = new HashSet<Paquete>();
            this.Rental = new HashSet<Rental>();
            this.Empresa_TipoEmpresa = new HashSet<Empresa_TipoEmpresa>();
            this.TarifaCarro = new HashSet<TarifaCarro>();
            this.TemporadaAvion = new HashSet<TemporadaAvion>();
            this.TemporadaEmpresa = new HashSet<TemporadaEmpresa>();
        }
    
        public int idEmpresa { get; set; }
        public string nombre_empresa { get; set; }
        public string foto_empresa { get; set; }
        public string direccion_empresa { get; set; }
        public string telefono_empresa { get; set; }
    
        public virtual ICollection<Avion> Avion { get; set; }
        public virtual ICollection<Carro> Carro { get; set; }
        public virtual ICollection<Excursion> Excursion { get; set; }
        public virtual ICollection<OficinaRenta> OficinaRenta { get; set; }
        public virtual ICollection<Paquete> Paquete { get; set; }
        public virtual ICollection<Rental> Rental { get; set; }
        public virtual ICollection<Empresa_TipoEmpresa> Empresa_TipoEmpresa { get; set; }
        public virtual ICollection<TarifaCarro> TarifaCarro { get; set; }
        public virtual ICollection<TemporadaAvion> TemporadaAvion { get; set; }
        public virtual ICollection<TemporadaEmpresa> TemporadaEmpresa { get; set; }
    }
}
