//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa_TipoEmpresa
    {
        public int idunionet { get; set; }
        public Nullable<int> idtipoempresa { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<bool> asignado { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Tipo_Empresa Tipo_Empresa { get; set; }
    }
}
