//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public Hotel()
        {
            this.Temporada_Hotel = new HashSet<Temporada_Hotel>();
            this.Temporada_Reduccion = new HashSet<Temporada_Reduccion>();
            this.Temporada_Suplemento = new HashSet<Temporada_Suplemento>();
            this.Reduccion_Hotel = new HashSet<Reduccion_Hotel>();
            this.Suplemento_Hotel = new HashSet<Suplemento_Hotel>();
            this.Tipol_HotelTipol = new HashSet<Tipol_HotelTipol>();
        }
    
        public int idHotel { get; set; }
        public string nombre_hotel { get; set; }
        public string descripcion_hotel { get; set; }
        public string direccion { get; set; }
        public string foto_hotel1 { get; set; }
        public string foto_hote2 { get; set; }
        public string foto_hotel3 { get; set; }
        public int idCategoria { get; set; }
        public int idCadena { get; set; }
        public int idDestino { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string sitioWeb { get; set; }
        public string facilidades { get; set; }
    
        public virtual Cadena Cadena { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Destino Destino { get; set; }
        public virtual ICollection<Temporada_Hotel> Temporada_Hotel { get; set; }
        public virtual ICollection<Temporada_Reduccion> Temporada_Reduccion { get; set; }
        public virtual ICollection<Temporada_Suplemento> Temporada_Suplemento { get; set; }
        public virtual ICollection<Reduccion_Hotel> Reduccion_Hotel { get; set; }
        public virtual ICollection<Suplemento_Hotel> Suplemento_Hotel { get; set; }
        public virtual ICollection<Tipol_HotelTipol> Tipol_HotelTipol { get; set; }
    }
}
