//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripAgencyEntities : DbContext
    {
        public TripAgencyEntities()
            : base("name=TripAgencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anno> Anno { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Cadena> Cadena { get; set; }
        public virtual DbSet<Carro> Carro { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<CategTarifAvion> CategTarifAvion { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<DestinoRental> DestinoRental { get; set; }
        public virtual DbSet<DestinoVuelo> DestinoVuelo { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Empresa_TipoEmpresa> Empresa_TipoEmpresa { get; set; }
        public virtual DbSet<Estacion> Estacion { get; set; }
        public virtual DbSet<Excursion> Excursion { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<NomAvionClase> NomAvionClase { get; set; }
        public virtual DbSet<NomClaseCatTarAvi> NomClaseCatTarAvi { get; set; }
        public virtual DbSet<NomTempAvionClase> NomTempAvionClase { get; set; }
        public virtual DbSet<NomTempRedHotel> NomTempRedHotel { get; set; }
        public virtual DbSet<NomTempSupHotel> NomTempSupHotel { get; set; }
        public virtual DbSet<NomTempTipHotel> NomTempTipHotel { get; set; }
        public virtual DbSet<OficinaRenta> OficinaRenta { get; set; }
        public virtual DbSet<OficPerCar> OficPerCar { get; set; }
        public virtual DbSet<OrigenRental> OrigenRental { get; set; }
        public virtual DbSet<OrigenVuelo> OrigenVuelo { get; set; }
        public virtual DbSet<Pai> Pai { get; set; }
        public virtual DbSet<Paquete> Paquete { get; set; }
        public virtual DbSet<Rango> Rango { get; set; }
        public virtual DbSet<Rangos_Tarifa> Rangos_Tarifa { get; set; }
        public virtual DbSet<Reduccion> Reduccion { get; set; }
        public virtual DbSet<Reduccion_Hotel> Reduccion_Hotel { get; set; }
        public virtual DbSet<Rental> Rental { get; set; }
        public virtual DbSet<Subdestino> Subdestino { get; set; }
        public virtual DbSet<Suplemento> Suplemento { get; set; }
        public virtual DbSet<Suplemento_Hotel> Suplemento_Hotel { get; set; }
        public virtual DbSet<TarifaCarro> TarifaCarro { get; set; }
        public virtual DbSet<Tarificacion> Tarificacion { get; set; }
        public virtual DbSet<Temporada> Temporada { get; set; }
        public virtual DbSet<Temporada_Hotel> Temporada_Hotel { get; set; }
        public virtual DbSet<Temporada_Reduccion> Temporada_Reduccion { get; set; }
        public virtual DbSet<Temporada_Suplemento> Temporada_Suplemento { get; set; }
        public virtual DbSet<TemporadaAvion> TemporadaAvion { get; set; }
        public virtual DbSet<TemporadaEmpresa> TemporadaEmpresa { get; set; }
        public virtual DbSet<TemporadaExcursion> TemporadaExcursion { get; set; }
        public virtual DbSet<TemporadaPaquete> TemporadaPaquete { get; set; }
        public virtual DbSet<TemporadaRental> TemporadaRental { get; set; }
        public virtual DbSet<Tipo_Empresa> Tipo_Empresa { get; set; }
        public virtual DbSet<Tipo_Tarifa> Tipo_Tarifa { get; set; }
        public virtual DbSet<TipoAvion> TipoAvion { get; set; }
        public virtual DbSet<Tipologia_Carro> Tipologia_Carro { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<Tipol_HotelTipol> Tipol_HotelTipol { get; set; }
        public virtual DbSet<Tipologia> Tipologia { get; set; }
    }
}
