//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomClaseCatTarAvi
    {
        public int idNomClaseCatTarAvi { get; set; }
        public Nullable<int> idClase { get; set; }
        public Nullable<int> idCategTarifAvion { get; set; }
        public Nullable<bool> asignado { get; set; }
    
        public virtual CategTarifAvion CategTarifAvion { get; set; }
        public virtual Clase Clase { get; set; }
    }
}
