//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomTempRedHotel
    {
        public int idtemphotred { get; set; }
        public int idTemporada_Reduccion { get; set; }
        public int idreduccion { get; set; }
        public Nullable<double> tarifa { get; set; }
        public Nullable<int> idtipotarifa { get; set; }
    
        public virtual Reduccion Reduccion { get; set; }
        public virtual Temporada_Reduccion Temporada_Reduccion { get; set; }
        public virtual Tipo_Tarifa Tipo_Tarifa { get; set; }
    }
}
