//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NomTempTipHotel
    {
        public int idtemphottip { get; set; }
        public int idTemporadaHotel { get; set; }
        public int idTiologia { get; set; }
        public Nullable<double> tarifa { get; set; }
        public Nullable<int> idtipotarifa { get; set; }
        public Nullable<int> maxadult { get; set; }
        public Nullable<int> maxninno { get; set; }
        public Nullable<int> minadult { get; set; }
        public Nullable<int> minninno { get; set; }
    
        public virtual Temporada_Hotel Temporada_Hotel { get; set; }
        public virtual Tipo_Tarifa Tipo_Tarifa { get; set; }
        public virtual Tipologia Tipologia { get; set; }
    }
}
