//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OficPerCar
    {
        public int idOficCar { get; set; }
        public Nullable<int> idCarro { get; set; }
        public Nullable<int> idOficina { get; set; }
    
        public virtual Carro Carro { get; set; }
        public virtual OficinaRenta OficinaRenta { get; set; }
    }
}
