//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pai
    {
        public Pai()
        {
            this.Destino = new HashSet<Destino>();
        }
    
        public int idPais { get; set; }
        public string pais { get; set; }
        public string foto { get; set; }
    
        public virtual ICollection<Destino> Destino { get; set; }
    }
}
