//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rango
    {
        public Rango()
        {
            this.Rangos_Tarifa = new HashSet<Rangos_Tarifa>();
        }
    
        public int idrango { get; set; }
        public string rango1 { get; set; }
    
        public virtual ICollection<Rangos_Tarifa> Rangos_Tarifa { get; set; }
    }
}
