//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rangos_Tarifa
    {
        public int idrangtar { get; set; }
        public Nullable<int> idcondtarifa { get; set; }
        public Nullable<int> idrango { get; set; }
        public Nullable<bool> asignado { get; set; }
        public Nullable<double> tarifa { get; set; }
    
        public virtual Rango Rango { get; set; }
        public virtual TarifaCarro TarifaCarro { get; set; }
    }
}
