//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reduccion
    {
        public Reduccion()
        {
            this.NomTempRedHotel = new HashSet<NomTempRedHotel>();
            this.Reduccion_Hotel = new HashSet<Reduccion_Hotel>();
        }
    
        public int idReduccion { get; set; }
        public string reduccion1 { get; set; }
        public string descripcion_reduccion { get; set; }
    
        public virtual ICollection<NomTempRedHotel> NomTempRedHotel { get; set; }
        public virtual ICollection<Reduccion_Hotel> Reduccion_Hotel { get; set; }
    }
}
