//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public Rental()
        {
            this.TemporadaRental = new HashSet<TemporadaRental>();
        }
    
        public int idRental { get; set; }
        public string nombre { get; set; }
        public string foto { get; set; }
        public string descripcion { get; set; }
        public int idDestinoRental { get; set; }
        public int idOrigenRental { get; set; }
        public Nullable<int> idEmpresa { get; set; }
    
        public virtual DestinoRental DestinoRental { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual OrigenRental OrigenRental { get; set; }
        public virtual ICollection<TemporadaRental> TemporadaRental { get; set; }
    }
}
