//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subdestino
    {
        public int idSubdestino { get; set; }
        public string subdestino1 { get; set; }
        public string descripcion_subdestino { get; set; }
        public string foto_sub1 { get; set; }
        public string foto_sub2 { get; set; }
        public int iddestino { get; set; }
    
        public virtual Destino Destino { get; set; }
    }
}
