//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suplemento
    {
        public Suplemento()
        {
            this.NomTempSupHotel = new HashSet<NomTempSupHotel>();
            this.Suplemento_Hotel = new HashSet<Suplemento_Hotel>();
        }
    
        public int idSuplemento { get; set; }
        public string suplemento1 { get; set; }
        public string descripcion_suplemento { get; set; }
    
        public virtual ICollection<NomTempSupHotel> NomTempSupHotel { get; set; }
        public virtual ICollection<Suplemento_Hotel> Suplemento_Hotel { get; set; }
    }
}
