//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifaCarro
    {
        public TarifaCarro()
        {
            this.Rangos_Tarifa = new HashSet<Rangos_Tarifa>();
        }
    
        public int idcondtarifa { get; set; }
        public double valor { get; set; }
        public double seguro { get; set; }
        public double deposito { get; set; }
        public string descripcion { get; set; }
        public int idAnno { get; set; }
        public int idTemporada { get; set; }
        public int idtipologia_carro { get; set; }
        public int idEmpresa { get; set; }
        public Nullable<int> idTemporadaEmpresa { get; set; }
    
        public virtual Anno Anno { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Rangos_Tarifa> Rangos_Tarifa { get; set; }
        public virtual Temporada Temporada { get; set; }
        public virtual Tipologia_Carro Tipologia_Carro { get; set; }
        public virtual TemporadaEmpresa TemporadaEmpresa { get; set; }
    }
}
