//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarificacion
    {
        public Tarificacion()
        {
            this.Tipologia = new HashSet<Tipologia>();
        }
    
        public int idTarificacion { get; set; }
        public string nombre { get; set; }
        public bool pack { get; set; }
        public bool hab { get; set; }
        public bool casa { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Tipologia> Tipologia { get; set; }
    }
}
