//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemporadaExcursion
    {
        public int idtemporadaexcursion { get; set; }
        public string periodo { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime inicio { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fin { get; set; }
        public string descripcion_periodo { get; set; }
        public int idanno { get; set; }
        public Nullable<double> precio_tarifa { get; set; }
        public Nullable<int> idExcursion { get; set; }
        public int idEstacion { get; set; }
        public int idTemporada { get; set; }
    
        public virtual Anno Anno { get; set; }
        public virtual Estacion Estacion { get; set; }
        public virtual Excursion Excursion { get; set; }
        public virtual Temporada Temporada { get; set; }
    }
}
