//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporada_Reduccion
    {
        public Temporada_Reduccion()
        {
            this.NomTempRedHotel = new HashSet<NomTempRedHotel>();
        }
    
        public int idTemporada_Reduccion { get; set; }
        public string periodo { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> inicio { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fin { get; set; }
        public int idtemporada { get; set; }
        public int idanno { get; set; }
        public Nullable<double> valor { get; set; }
        public Nullable<int> idhotel { get; set; }
        public int idEstacion { get; set; }
    
        public virtual Anno Anno { get; set; }
        public virtual Estacion Estacion { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<NomTempRedHotel> NomTempRedHotel { get; set; }
        public virtual Temporada Temporada { get; set; }
    }
}
