//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporada_Hotel
    {
        public Temporada_Hotel()
        {
            this.NomTempTipHotel = new HashSet<NomTempTipHotel>();
        }
    
        public int idTemporadaHotel { get; set; }
        public string periodo { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime inicio { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime fin { get; set; }
        public string descripcion_periodo { get; set; }
        public int idanno { get; set; }
        public int idhotel { get; set; }
        public int idEstacion { get; set; }
        public int idTemporada { get; set; }
        public Nullable<double> tarifa { get; set; }
    
        public virtual Anno Anno { get; set; }
        public virtual Estacion Estacion { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<NomTempTipHotel> NomTempTipHotel { get; set; }
        public virtual Temporada Temporada { get; set; }
    }
}
