//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temporada_Suplemento
    {
        public Temporada_Suplemento()
        {
            this.NomTempSupHotel = new HashSet<NomTempSupHotel>();
        }
    
        public int idSuplementoHotel { get; set; }
        public string periodo { get; set; }
        public System.DateTime inicio { get; set; }
        public System.DateTime fin { get; set; }
        public int idanno { get; set; }
        public Nullable<double> valor { get; set; }
        public int idhotel { get; set; }
        public int idEstacion { get; set; }
        public int idTemporada { get; set; }
    
        public virtual Anno Anno { get; set; }
        public virtual Estacion Estacion { get; set; }
        public virtual Hotel Hotel { get; set; }
        public virtual ICollection<NomTempSupHotel> NomTempSupHotel { get; set; }
        public virtual Temporada Temporada { get; set; }
    }
}
