//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripAgency.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Empresa
    {
        public Tipo_Empresa()
        {
            this.Empresa_TipoEmpresa = new HashSet<Empresa_TipoEmpresa>();
        }
    
        public int idtipoempresa { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Empresa_TipoEmpresa> Empresa_TipoEmpresa { get; set; }
    }
}
